### ISSUE TITLE
Mouse cursor does not change on hover

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#6]
Should be an easy one...

![image](https://user-images.githubusercontent.com/2659746/94891308-891c2400-0436-11eb-85bf-e4d033f26602.png)

**Comment by dimitarangelkov** [comment]
@circuitfive pretty simple one. The hover issue appears because the anchor tag is missing "href" attribute. Unfortunately will be more complicated if try to modify it, since the entire phrase including the anchor tag is part of all translation files of the plugin, so it is multiplied several times. Luckily there is a dedicated css class for this specific tag, so the easiest solution was just to change the mouse cursor to `pointer` for it.
